version: '3.9'

services:
  api1: &api1
    hostname: api1
    build: ./src
    depends_on: 
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__AppDbContext: Host=db;Username=postgres;Password=postgres;Database=rinha;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=30;
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "175MB"
  
  api2:
    <<: *api1
    user: root
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__AppDbContext: Host=db;Username=postgres;Password=postgres;Database=rinha;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=30;
      DOTNET_DiagnosticPorts: /diag/dotnet-monitor2.sock
    volumes:
      - "./diag:/diag"
  monitor2:
    image: mcr.microsoft.com/dotnet/monitor:8
    environment:
      DOTNETMONITOR_Storage__DefaultSharedPath: /diag
      DOTNETMONITOR_Metrics__Endpoints: http://+:52325
      DOTNETMONITOR_Urls: http://+:52323
      DOTNETMONITOR_DiagnosticPort__ConnectionMode: listen
      DOTNETMONITOR_DiagnosticPort__EndpointName: /diag/dotnet-monitor2.sock
      DOTNETMONITOR_Metrics__Providers__0__ProviderName: Npgsql
      DOTNETMONITOR_Metrics__Providers__1__ProviderName: Microsoft.EntityFrameworkCore
    command: [ "collect", "--no-auth" ]
    volumes:
      - "./diag:/diag"
    ports:
      - "52323:52323"
      - "52325:52325"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    depends_on:
      - postgres-exporter
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
    command: postgres -c max_connections=100
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--dbname=rinha",
          "--username=postgres"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/rinha?sslmode=disable"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    healthcheck:
      test: [ "CMD", "wget", "-c", "http://localhost:9090" ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
  grafana:
      image: grafana/grafana-oss
      ports:
        - "3000:3000"
      volumes:
        # https://grafana.com/docs/grafana/latest/administration/provisioning/
        - "./grafana/provisioning/:/etc/grafana/provisioning/"
        - "./grafana/dashboards/:/var/lib/grafana/dashboards/"
      depends_on:
        prometheus:
          condition: service_healthy
      healthcheck:
        test: [ "CMD", "grafana-cli", "plugins", "ls" ]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 20s
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafaelpadovezi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"