POST http://localhost:5047/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 51000,
  "tipo" : "d",
  "descricao" : "1"
}

###
GET http://localhost:5047/clientes/1/extrato
Accept: application/json

###
POST http://localhost:5047/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1.2,
  "tipo" : "c",
  "descricao" : "descricao"
}